var files_dup =
[
    [ "build", "dir_4fef79e7177ba769987a8da36c892c5f.html", "dir_4fef79e7177ba769987a8da36c892c5f" ],
    [ "AlarmSystem.cpp", "_alarm_system_8cpp.html", null ],
    [ "AlarmSystem.h", "_alarm_system_8h.html", "_alarm_system_8h" ],
    [ "Building.cpp", "_building_8cpp.html", null ],
    [ "Building.h", "_building_8h.html", "_building_8h" ],
    [ "BuildingView.cpp", "_building_view_8cpp.html", null ],
    [ "BuildingView.h", "_building_view_8h.html", "_building_view_8h" ],
    [ "Door.cpp", "_door_8cpp.html", null ],
    [ "Door.h", "_door_8h.html", "_door_8h" ],
    [ "Employee.cpp", "_employee_8cpp.html", null ],
    [ "Employee.h", "_employee_8h.html", "_employee_8h" ],
    [ "EventLog.cpp", "_event_log_8cpp.html", null ],
    [ "EventLog.h", "_event_log_8h.html", "_event_log_8h" ],
    [ "guard.cpp", "guard_8cpp.html", null ],
    [ "guard.h", "guard_8h.html", "guard_8h" ],
    [ "Intruder.cpp", "_intruder_8cpp.html", null ],
    [ "Intruder.h", "_intruder_8h.html", "_intruder_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "mainwindow.cpp", "mainwindow_8cpp.html", null ],
    [ "mainwindow.h", "mainwindow_8h.html", "mainwindow_8h" ],
    [ "Person.cpp", "_person_8cpp.html", null ],
    [ "Person.h", "_person_8h.html", "_person_8h" ],
    [ "Room.cpp", "_room_8cpp.html", null ],
    [ "Room.h", "_room_8h.html", "_room_8h" ],
    [ "Sensor.cpp", "_sensor_8cpp.html", null ],
    [ "Sensor.h", "_sensor_8h.html", "_sensor_8h" ],
    [ "Simulation.cpp", "_simulation_8cpp.html", null ],
    [ "Simulation.h", "_simulation_8h.html", "_simulation_8h" ]
];